version: "3.9"
services:
  app:
    build: .
    ports:
      - 8501:8501
    volumes:
      - .:/app
      - ./configs/streamlit.toml:/root/.streamlit/config.toml
      - app_module_cache:/root/.cache
volumes:
  app_module_cache:

